### ISSUE TITLE
受け取ったjsonデータを、配列として、格納したい。

### ISSUE THREAD

**Issue by tozan-miyage** [tozan-miyage/N-RET3#1]
https://github.com/tozan-miyage/N-RET3/blob/d6edc7cbcb54f7a33c856e05e22d7ea46c497edb/resources/views/group/play.blade.php#L79

データをajaxで取り出せることができたので、これを配列としてpublic/js/typing.jsにある変数に格納したい。
変数名は、
①en_text_subject
②ja_text_subject
③img_subject
の３つ。

**Comment by hideyasu2015** [comment]
確認ですが、JavaScriptに保存する目的は、タイピングが１つ終わったら、次の問題を表示するということで良かったですか？
セットする素材は５つでしたっけ？
５つ以上ある場合はどうしますか？
５つ未満の場合はどうしますか？

**Comment by tozan-miyage** [comment]
目的は、おっしゃる通りです。１つ終わったら、次の問題に移りたいです。
セットできる素材は、いくつであっても、対応できるようにしたいです。
typing.jsのコードでは、最後の素材が終わったら、最初の素材に戻るようにプログラムされています。
