### ISSUE TITLE
buttonのfocusを外したい。blur()の使い方は当たっているのでしょうか？

### ISSUE THREAD

**Issue by tozan-miyage** [tozan-miyage/N-RET3#5]
https://github.com/tozan-miyage/N-RET3/blob/eea28f40fa68dbe7a80f18eea6853eb230197529/public/js/typing.js#L194

エラー文：
Uncaught TypeError: main_word_submit.blur is not a function
    at mainWordBtnBlur (typing.js:186)
    at typing.js:194
mainWordBtnBlur @ typing.js:186
(anonymous) @ typing.js:194

ーーーーーー現在の状況ーーーーーー
     タイピング画面の左サイドmenuの単語（main_word)をクリックすると、素材(material)が表示されます。
     ですが、menuの単語にfocusが当たったまま、タイピングを始めると、挙動がおかしくなります。

     適当な場所で一度クリックをすると、focusが外れるので、そこからタイピングを始めると、問題なく動きます。

ーーーーーー改善したいことーーーーーーーー
     menuの単語に、focusが当たったまま、タイピングを始めても、focusが外れるようにしたい。

ーーーーーー試したことーーーーーーーー
     keyイベント（タイピング）が発生したらblur()でフォーカスを外す。

     ①ボタンの要素を取得
     const main_word_submit = document.getElementsByClassName("main_word_submit");

     ②フォーカスを外すメソッドを定義
     const mainWordBtnBlur = () => {
             main_word_submit.blur();
      }

     ③keyイベントが発生したら実行
     mainWordBtnBlur();

ーーーーーー以上ーーーーーーー
     エラー文に関数が定義されていないと出ているので、どんな書き方が正しいのか教えていただきたいです。どうぞよろしくお 
     願いします。

**Comment by hideyasu2015** [comment]
宮里さん
まずblur()ですが、inputタグに対してフォーカスを当てる、外すものです。
今はmain_word_submit は buttonタグで書いていますので、当然動きません。
今は、コメントアウトして外しています。
動くようになりましたが、どのように挙動がおかしいのか、具体的に教えていただけますか？

**Comment by hideyasu2015** [comment]
これでスコープがはずれました。
```
   //URI(/api/materialapi）に接続・dataobjectを渡す      
    $.post('/api/materialapi', dataobject).done(function(data) {
      console.log( form.find('.main_word_submit')[0]);
      //tokuhara add
      form.find('.main_word_submit')[0].blur();
```
